spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: false
  resources:
    add-mappings: true
  output:
    ansi:
      enabled: always
server:
  address: localhost
  port: 8888